[project]
name = "llm-symbolic-interpreter"
version = "0.1.0"
description = "LLM-powered symbolic interpreter"
authors = [
    {name = "asgupta"}
]
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "pydantic (>=2.12.5,<3.0.0)",
    "anthropic (>=0.84.0,<0.85.0)",
    "openai (>=2.24.0,<3.0.0)",
    "tree-sitter (>=0.25.2,<0.26.0)",
    "tree-sitter-language-pack (>=0.13.0,<0.14.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
